# VacationPy
----

#### Note
* Keep an eye on your API usage. Use https://developers.google.com/maps/reporting/gmp-reporting as reference for how to monitor your usage and billing.

* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [2]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [14]:

vacay_df=pd.read_csv('output_data/clean_city_data.csv').reset_index()
vacay_df.drop(["level_0","Unnamed: 0", "index"], axis=1, inplace=True)
vacay_df

,City,Latitude,Longitude,Max Temperature (Celsius),Humidity (%),Cloudiness (%),Wind Speed (mph),Country,Date
0,Namatanai,-3.6667,152.4333,27.31,81,99,3.14,PG,02/04/21 02:20
1,Bredasdorp,-34.5322,20.0403,22.00,68,13,2.06,ZA,02/04/21 02:16
2,Chara,56.9064,118.2631,-25.50,78,100,0.25,RU,02/04/21 02:20
3,Puerto Ayora,-0.7393,-90.3518,24.44,94,98,3.53,EC,02/04/21 02:20
4,New Norfolk,-42.7826,147.0587,26.67,48,93,1.34,AU,02/04/21 02:20
...,...,...,...,...,...,...,...,...,...
559,Arman',59.7000,150.1667,-18.22,81,61,9.06,RU,02/04/21 02:23
560,San Martín,-33.0810,-68.4681,18.00,63,0,1.29,AR,02/04/21 02:23
561,Sechura,-5.5569,-80.8222,23.23,69,97,3.46,PE,02/04/21 02:23
562,Panabá,21.2833,-88.2667,15.41,89,0,2.32,MX,02/04/21 02:23
563,Egvekinot,66.3167,-179.1667,-34.30,82,13,7.12,RU,02/04/21 02:23

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [17]:
# Configure gmaps with API key
gmaps.configure(api_key=g_key)

In [18]:
# Store 'Lat' and 'Lng' into  locations 
locations = vacay_df[["Latitude", "Longitude"]].astype(float)

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure